// Userland versioning — pure JS, NO system `git` dependency.
//
// Phase 2c/3 built the Userland safety runway (snapshot / revert / auto-rollback)
// on a git REPO, originally by shelling out to the system `git` binary. That
// assumed git was installed and silently degraded when it wasn't. This module
// replaces those calls with **isomorphic-git** (pure JavaScript) so the runway
// works identically on any machine — packaged, no PATH, no git — with the diff
// text generated by **jsdiff**. The IPC handlers in index.ts are thin wrappers
// over these functions; the logic lives here so it can be unit-tested directly
// against a throwaway repo.

import git from 'isomorphic-git'
import fs from 'node:fs'
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { createTwoFilesPatch } from 'diff'

// isomorphic-git wants an FsClient; Node's `fs` module satisfies it. Cast via the
// init options' fs type so we don't depend on a named type export.
const FS = fs as unknown as Parameters<typeof git.init>[0]['fs']

// y never touches the user's global git identity — author is pinned per commit.
const AUTHOR = { name: 'y', email: 'y@localhost' }

export interface SnapResult {
  ok: boolean
  hash?: string
  count?: number
  error?: string
}

export interface DiffResult {
  ok: boolean
  dirty?: boolean
  diff?: string
  hash?: string
  count?: number
  error?: string
}

async function headOid(dir: string): Promise<string | null> {
  try {
    return await git.resolveRef({ fs: FS, dir, ref: 'HEAD' })
  } catch {
    return null // no repo / no commits yet
  }
}

async function shortHash(dir: string): Promise<string> {
  const oid = await headOid(dir)
  return oid ? oid.slice(0, 7) : ''
}

async function commitCount(dir: string): Promise<number> {
  try {
    return (await git.log({ fs: FS, dir, ref: 'HEAD' })).length
  } catch {
    return 0
  }
}

// `git add -A`: stage every change, including deletions (the documented
// statusMatrix pattern — worktreeStatus 0 means the file is gone → remove it).
async function stageAll(dir: string): Promise<void> {
  const status = await git.statusMatrix({ fs: FS, dir })
  await Promise.all(
    status.map(([filepath, , worktreeStatus]) =>
      worktreeStatus === 0
        ? git.remove({ fs: FS, dir, filepath })
        : git.add({ fs: FS, dir, filepath })
    )
  )
}

// A file whose working-tree content differs from HEAD.
interface Change {
  filepath: string
  oldText: string // content at HEAD ('' if the file is new)
  newText: string // content on disk ('' if the file was deleted)
}

// The pending changes vs HEAD, compared by ACTUAL CONTENT.
//
// We intentionally do NOT trust statusMatrix's WORKDIR column for detection:
// isomorphic-git caches the index's stat (size+mtime) and skips re-hashing when
// they match, so a same-size edit within the same mtime-second is misreported as
// unchanged. statusMatrix is still reliable for *enumerating* the file paths
// (HEAD ∪ workdir ∪ index) — we just decide changed/not by reading the bytes.
async function changedFiles(dir: string): Promise<Change[]> {
  const oid = await headOid(dir)
  const rows = await git.statusMatrix({ fs: FS, dir })
  const out: Change[] = []
  for (const [filepath] of rows) {
    let oldText = ''
    if (oid) {
      try {
        const { blob } = await git.readBlob({ fs: FS, dir, oid, filepath })
        oldText = new TextDecoder().decode(blob)
      } catch {
        oldText = '' // not present in HEAD
      }
    }
    let newText = ''
    try {
      newText = await readFile(join(dir, filepath), 'utf-8')
    } catch {
      newText = '' // deleted on disk
    }
    if (oldText !== newText) out.push({ filepath, oldText, newText })
  }
  return out
}

async function isDirty(dir: string): Promise<boolean> {
  return (await changedFiles(dir)).length > 0
}

// Deterministic `reset --hard <oid>`. We do NOT use git.checkout here: it skips
// rewriting a working file when the index already matches the target (so it
// won't discard same-HEAD dirty edits), and its handling of files absent from
// the target is unspecified. Instead we materialize the target tree onto disk
// ourselves, delete everything else, and rebuild the index — fully predictable.
async function resetHard(dir: string, oid: string): Promise<void> {
  const targetFiles = await git.listFiles({ fs: FS, dir, ref: oid })
  const targetSet = new Set(targetFiles)

  // 1. Write each target file's exact content to disk.
  for (const filepath of targetFiles) {
    const { blob } = await git.readBlob({ fs: FS, dir, oid, filepath })
    const abs = join(dir, filepath)
    await mkdir(dirname(abs), { recursive: true }).catch(() => {})
    await writeFile(abs, blob)
  }

  // 2. Delete any file on disk / in the index that the target doesn't have.
  const rows = await git.statusMatrix({ fs: FS, dir })
  for (const [filepath] of rows) {
    if (!targetSet.has(filepath)) {
      await rm(join(dir, filepath), { force: true }).catch(() => {})
    }
  }

  // 3. Point the branch at the target, then rebuild the index from the restored
  //    working tree so working == index == HEAD (a clean status).
  const branch = (await git.currentBranch({ fs: FS, dir, fullname: false })) || 'master'
  await git.writeRef({ fs: FS, dir, ref: `refs/heads/${branch}`, value: oid, force: true })
  const after = await git.statusMatrix({ fs: FS, dir })
  await Promise.all(
    after.map(([filepath, , workdir]) =>
      workdir === 0 ? git.remove({ fs: FS, dir, filepath }) : git.add({ fs: FS, dir, filepath })
    )
  )
}

// Init the repo (if needed) and make the first save point. Idempotent.
export async function ensureRepo(dir: string): Promise<void> {
  if (!fs.existsSync(join(dir, '.git'))) {
    await git.init({ fs: FS, dir, defaultBranch: 'master' })
  }
  if ((await headOid(dir)) === null) {
    await stageAll(dir)
    await git.commit({ fs: FS, dir, author: AUTHOR, message: 'initial userland' })
  }
}

// Snapshot = commit the current state (a save point). No-ops if nothing changed.
export async function snapshot(dir: string): Promise<SnapResult> {
  try {
    if (await isDirty(dir)) {
      await stageAll(dir)
      await git.commit({
        fs: FS,
        dir,
        author: AUTHOR,
        message: `snapshot ${new Date().toISOString()}`
      })
    }
    return { ok: true, hash: await shortHash(dir), count: await commitCount(dir) }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}

// Revert = one step of undo:
//  - uncommitted edits present → discard them, restore the last snapshot
//  - already clean             → step back to the previous snapshot
export async function revert(dir: string): Promise<SnapResult> {
  try {
    const oid = await headOid(dir)
    if (!oid) return { ok: false, error: 'No snapshot to revert to.' }
    if (await isDirty(dir)) {
      await resetHard(dir, oid)
    } else {
      const { commit } = await git.readCommit({ fs: FS, dir, oid })
      const parent = commit.parent[0]
      if (!parent) return { ok: false, error: 'No earlier snapshot to revert to.' }
      await resetHard(dir, parent)
    }
    return { ok: true, hash: await shortHash(dir), count: await commitCount(dir) }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}

// The pending change since the last snapshot, as a unified diff (jsdiff). Built
// straight from the working tree vs the HEAD blobs — no staging side effects.
export async function diff(dir: string): Promise<DiffResult> {
  try {
    const hash = await shortHash(dir)
    const count = await commitCount(dir)
    const changed = await changedFiles(dir)
    if (changed.length === 0) return { ok: true, dirty: false, diff: '', hash, count }

    let out = ''
    for (const { filepath, oldText, newText } of changed) {
      out += createTwoFilesPatch(`a/${filepath}`, `b/${filepath}`, oldText, newText, '', '', {
        context: 3
      })
    }
    return { ok: true, dirty: true, diff: out, hash, count }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}
